### ISSUE TITLE
Develop Input Form in HTML

### ISSUE THREAD

**Issue by LeeGee64** [LeeGee64/-100DevsZodiacDetermination#1]
In the Index File:

- Create a simple welcome message that explains the purpose of the App and the required Info
- create a form that takes the first name of the User, their birth month and birth date
- create two div elements that will be appended with the message to the user, the proper zodiac sign, and an image of the sign

**Comment by MaryShodiya** [comment]
I will like to take this one Lee

**Comment by MaryShodiya** [comment]
Okay I think I just noticed aarbaiza already took this
