### ISSUE TITLE
Addit'l HTML Page

### ISSUE THREAD

**Issue by LeeGee64** [LeeGee64/-100DevsZodiacDetermination#15]
We need another html page where we will return the Zodiac results after the User submits their birthday

1. Title file 'Results.html'
2. Use the same bkgrnd image and text styles as seen in index.html
3. Include three divs for the Zodiac name, image and description
4. Add the file into the hmtl folder

Once the file is added, we can update the server and main js files

**Comment by nooska44** [comment]
Hi I am happy to give this a try.
