### ISSUE TITLE
Folder of Zodiac Images

### ISSUE THREAD

**Issue by LeeGee64** [LeeGee64/-100DevsZodiacDetermination#4]
Create a folder with all twelve zodiac images. Please keep the images relatively small (no bigger 500px by 500px)

**Comment by shaylalewis** [comment]
I'd like to take this on!

**Comment by nooska44** [comment]
I'm happy to help

**Comment by LeeGee64** [comment]
I'll create an images folder and then you both can add images once I make you collaborators

**Comment by leerivera** [comment]
I created all the images and I have them saved to my computer. I don't know how to push them up. Could you walk me through it please?

**Comment by crystalrena15** [comment]
@leerivera Drag your image to the content area Submit the issue After submitting the issue, github will show you the preview of your image. You can just right click, copy the URL and use it. This approach saves you from add-commit-push cycle. I didn't mean to close it

**Comment by leerivera** [comment]
thanks @crystalrena15 . I just did add commit push. I thought it was going to be more complicated but it was not.
