### ISSUE TITLE
App Read.me

### ISSUE THREAD

**Issue by LeeGee64** [LeeGee64/-100DevsZodiacDetermination#5]
We need a Read.me txt file based on the template we've seen in githubs shown in class. When I find the link, I can put it here as reference

**Comment by MaryShodiya** [comment]
Let me do this

**Comment by LeeGee64** [comment]
You got it

**Comment by MaryShodiya** [comment]
Gracias

**Comment by crystalrena15** [comment]
@LeeGee64 Hey did you find the link?

**Comment by crystalrena15** [comment]
@LeeGee64 https://github.com/alecortega/portfolio-template

I found it!
