### ISSUE TITLE
Zodiac Descriptions

### ISSUE THREAD

**Issue by LeeGee64** [LeeGee64/-100DevsZodiacDetermination#6]
A text file with brief descriptions of each Zodiac Sign. 

NOTE: Please don't plagiarize! It would be ideal if we could launch this app without any copyright problems

**Comment by ashton-martin** [comment]
I can take this one, and can use the template as reference once you find it (I may have missed that class so not sure which one you are talking about)

**Comment by LeeGee64** [comment]
The template is for the read.me file. The descriptions can look like however you want. Thanks!

**Comment by LeeGee64** [comment]
Thanks for the descriptions! These are amazing. I'm closing this issue and adding your text to our JS file
